import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    console.log("Index page did mount");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>
            <h1>This is the home page</h1>
            <h3>
              This is also one of the most unstyled page I have ever made...
            </h3>
            <h4>Check the links bellow:</h4>
            <ul>
              <li>
                <Link href="/about">About</Link>
                <br />
              </li>
              <li>
                <Link href="/terms">Terms of Use</Link>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
